### interface descriptor file ###
### note: will be parse as env varibles, so not use # at the end of line

idf:
  version: 0.1
  cactus:
    jumphost:
      bridges:
        admin: admin
        mgmt: mgmt
        public: public
      fixed_ips:
        admin: 192.168.117.1
        mgmt: 10.0.117.1
        public: 172.0.117.1
