### interface descriptor file ###
### note: will be parse as env varibles, so not use # at the end of line

idf:
  version: 0.1
  cactus:
    jumphost:
      bridges:
        admin: cactus_admin
        public: cactus_public
      fixed_ips:
        admin: 192.168.117.1
        public: 172.7.117.1
