---
cluster:
  domain: new.k8s
  version: v1.13.6
  enable_admission: NodeRestriction
  pod_cidr: 10.244.0.0/16
# service_cidr: 192.168.11.0/24
  states:
    cni: calico
    cri: docker
#    csi:
#    objects:
