---
cluster:
  domain: cactus.k8s
  version: v1.12.1
  pod_cidr: 10.244.0.0/16
# service_cidr: 192.168.11.0/24
  states:
    cni: calico
    cri: docker
#    csi:
    components:
      - dashboard
      - metrics-server
      - istio-demo.yaml
