---
cluster:
  domain: helm.k8s
  version: v1.16.4
#  pod_cidr: 10.44.0.0/16
  enable_admission: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
#  service_cidr: 192.168.11.0/24
  states:
    cni: calico/v3.8
    cri: docker
#    csi:
    objects:
      - helm
    helm:
      version: helm-v3.0.2-linux-amd64.tar.gz
#      # the installation will be like:
#      # 1. helm install <name> <path> --version <version> --namespace <namespace>
#      # 2. helm install <name> <url> --version <version> --namespace <namespace>
#      # 3. helm install <name> <path> --repo <url> --version <version> --namespace <namespace>
#      charts:
#        - flag: istio_init
#          name: istio-init
#          version: 
#          # path could be a chart reference, or a path to a packaged/unpackaged chart
#          path: install/kubernetes/helm/istio-init
#          # if path is not provided, url is the absoule URL of the chart
#          # otherwise, it refers to the repo url
#          url: https://github.com/istio/istio/releases/download/1.4.2/istio-1.4.2-linux.tar.gz
#          namespace: istio-system
#          args:
#            - --values: https://github.com/SerenaFeng/helm-charts/raw/master/istio/values-istio-1.2.2.yaml
#            - --set: kiali.enabled=true,kiali.dashboard.username=admin
