---
cluster:
  domain: helm.k8s
  version: v1.13.6
#  pod_cidr: 10.44.0.0/16
  enable_admission: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
#  service_cidr: 192.168.11.0/24
  states:
    cni: calico/v3.1.3
    cri: docker
#    csi:
    objects:
      - helm
    helm:
      version: v2.12.2
#      repos:
#        # flag is utilized to handle when name is not compatible with bash variable,
#        # such as istio-init can not be used as the bash variable name
#        - flag: istio
#          name: istio
#          url: http://harbor.oz/chartrepo/istio
