---
cluster:
  name: istio
  domain: istio.k8s
  version: v1.16.2
#  pod_cidr: 10.244.32.0/20
  enable_admission: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
#  service_cidr: 192.168.32.0/20
  states:
    cni: calico/v3.8
    cri: docker
#    csi:
    objects:
      - helm
    helm:
      version: helm-v3.0.2-linux-amd64.tar.gz
      charts:
        - flag: istio_init
          name: istio-init
          path: /home/serena/istio/istio-1.4.2/install/kubernetes/helm/istio-init
          namespace: istio-system
        - flag: istio
          name: istio
          path: /home/serena/istio/istio-1.4.2/install/kubernetes/helm/istio
          namespace: istio-system
          args:
            - --values: /home/serena/istio/istio-1.4.2/install/kubernetes/helm/istio/values-istio-demo.yaml
            - --set: global.controlPlaneSecurityEnabled=true,global.mtls.enabled=true
