---
cluster:
  name: istio
  domain: istio.k8s
  version: v1.13.6
#  pod_cidr: 10.244.32.0/20
  enable_admission: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
#  service_cidr: 192.168.32.0/20
  states:
    cni: calico
    cri: docker
#    csi:
    objects:
      - helm
    helm:
      version: v2.14.2
      charts:
        - flag: istio_init
          name: istio-init
          url: https://github.com/SerenaFeng/helm-charts/raw/master/istio/istio-init-1.2.2.tgz
          namespace: istio-system
        - flag: istio
          name: istio
          url: https://github.com/SerenaFeng/helm-charts/raw/master/istio/istio-1.2.2.tgz
          namespace: istio-system
          args:
            - --values: https://github.com/SerenaFeng/helm-charts/raw/master/istio/values-istio-1.2.2.yaml
