---
cluster:
  name: istio-cni
  domain: istio-cni.k8s
  version: v1.17.3
  image: ubuntu_bionic.qcow2
  pod_cidr: 10.244.0.0/16
  enable_admission: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
  runtime_config: api/all=true
  service_cidr: 192.168.11.0/24
  states:
    cni: calico/v3.8
    cri: docker
#    csi:
    istio:
      version: 1.4.6
      args:
#        - -f: /home/serena/k8s/cactus/config/scenario/istio-egress.yaml
#        - --set: profile=demo
        - --set: cni.enabled=true
#        - --set: values.global.mtls.enabled=false
#        - --set: values.global.controlPlaneSecurityEnabled=false
#        - --set: values.global.trustDomain=ori-td
      auto_inject: default
