---
cluster:
  domain: cactus.k8s
  version: v1.13.2
  pod_cidr: 10.244.0.0/16
  enable_admission: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
# service_cidr: 192.168.11.0/24
  states:
    cni: calico
    cri: docker
#    csi:
    objects:
      - helm
    helm:
      version: v2.12.2
#      repos:
        # a list in the schema: "repo_name|url"
#        - istio|http://harbor.oz/chartrepo/istio
      charts:
        # a list in the schema: "chart|release_name|version|namespace"
#        - istio/istio|istio|1.0.6|istio-system
        - https://github.com/SerenaFeng/helm-charts/raw/master/istio-1.0.6.tgz|istio||istio-system
