---
cluster:
  domain: cactus.k8s
  version: v1.13.2
  pod_cidr: 10.244.0.0/16
  enable_admission: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
# service_cidr: 192.168.11.0/24
  states:
    cni: calico
    cri: docker
#    csi:
    objects:
      - helm
    helm:
      version: v2.12.2
      charts:
        - name: istio
          repo: http://harbor.oz/chartrepo/istio
          version: 1.0.6
