---
cluster:
  name: smain
  #domain: istio.k8s
  version: v1.17.3
  image: ubuntu_bionic.qcow2
  pod_cidr: 10.5.1.0/24
  service_cidr: 192.5.1.0/24
  enable_admission: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
  runtime_config: api/all=true
  states:
    cni: calico/v3.8
    cri: docker
