---
cluster:
  name: xmain
  #domain: basic.k8s
  version: v1.18.6
  image: ubuntu_bionic.qcow2
  enable_admission: NodeRestriction
  runtime_config: api/all=true
  pod_cidr: 10.0.3.0/24
  service_cidr: 192.0.3.0/24
  states:
    cni: calico/v3.8
    cri: docker
#    csi:
#    objects:
